name: Mav-PaperTest-One
version: '${version}'
main: net.mavity.mavpapertestone.Mav_PaperTest_One
api-version: '1.20'
authors: [Mavity The Madity]
description: Mavity's first attempt at a paper plugin
commands:
  wiiu:
    description: WiiU
    usage: /wiiu